name: simple
on:
  workflow_dispatch:
jobs:
  build:
  runs-on: self-hosted
	  - label-1
  steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: |
        echo Hello, world!
        sleep 15
        echo Goodbye!
    - name: Run multi-line script
      run: |
        echo "${{github.workspace}}"
